Revert "CChunkData optimizations (#193)"
This reverts commit a1b97730bdd5029f3076269ce6e4a297883c8262.

Due to Errors
```
thread 'tokio-runtime-worker' panicked at pumpkin-protocol/src/client/play/c_chunk_data.rs:84:25:
index out of bounds: the len is 4096 but the index is 25374
```